server:
  port: 8888
---
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/naveenjava/git-configuration.git
          searchPaths: common,{application} #looking for sub directory
          timeout: 5
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh